---
title: "01 logistic回归"
date: "2026-04-03"
output: html_document
editor_options:
  markdown:
    wrap: 72
---

# Day 1：医学数据的整理与二分类结局的基本描述
目标：导入数据、处理变量类型、做基本描述，为 Logistic 做准备
核心内容：
  数据导入
  核心变量选择
  分类与连续变量处理
  缺失值概览
  分组描述
输出：描述性统计表
## 数据导入
```{r}
library(tidyverse)
data = read.csv("./data/metabric_cleaned_1500.csv")

```
## 核心变量选择 & 分类与连续变量处理
```{r}
data_analysis <- data %>% select(PATIENT_ID, TreatmentOutcome, AGE_AT_DIAGNOSIS,
                          LATERALITY, ER_STATUS, HER2_STATUS, TUMOR_STAGE) %>% 
                          mutate(TreatmentOutcome = factor(TreatmentOutcome),
                                 LATERALITY = factor(LATERALITY),
                                 ER_STATUS = factor(ER_STATUS),
                                 HER2_STATUS = factor(HER2_STATUS),
                                 TUMOR_STAGE = factor(TUMOR_STAGE))
```
## 缺失值概览
```{r}
data_analysis %>% summarise(across(everything(), ~ sum(is.na(.)))) %>% 
                  pivot_longer(everything(), names_to = "variable", values_to = "n_missing") %>% 
                  mutate(p_missing = n_missing / 1500)
```
## 分组描述
### 连续变量
```{r}
data_analysis %>% group_by(TreatmentOutcome) %>% 
      summarise(N = n(), Age_mean = mean(AGE_AT_DIAGNOSIS, na.rm=T),
                Age_std = sd(AGE_AT_DIAGNOSIS, na.rm=T),
                Age_median = median(AGE_AT_DIAGNOSIS, na.rm=T))
```
### 分类变量
```{r}
cat_by_outcome = function(var) {
  data_analysis %>% count(TreatmentOutcome, {{var}}) %>% 
    group_by(TreatmentOutcome) %>% mutate(prop = n / sum(n)) %>% ungroup()
}
```

```{r}
cat_by_outcome(var=LATERALITY)
```


