---
title: "02 logistic回归 批量单因素"
date: "2026-04-04"
output: html_document
editor_options:
  markdown:
    wrap: 72
---

# Day 2：单因素 Logistic 回归
目标：批量单因素回归，输出 OR、95%CI、P 值
核心内容：
     建立模型：glm(y ~ x, family = binomial())
     得到OR与置信区间
     批量建模
输出：单因素OR表

## 数据导入
```{r}
library(tidyverse)
library(broom)
data = read.csv("./data/metabric_cleaned_1500.csv")

```
## 核心变量选择 & 分类与连续变量处理
```{r}
data_analysis <- data %>% select(PATIENT_ID, TreatmentOutcome, AGE_AT_DIAGNOSIS,
                          LATERALITY, ER_STATUS, HER2_STATUS, TUMOR_STAGE) %>% 
                          mutate(TreatmentOutcome = factor(TreatmentOutcome),
                                 LATERALITY = factor(LATERALITY),
                                 ER_STATUS = factor(ER_STATUS),
                                 HER2_STATUS = factor(HER2_STATUS),
                                 TUMOR_STAGE = factor(TUMOR_STAGE))
```
## 数据清理 - 删除含有NA的行
```{r}
data_analysis <- data_analysis %>% drop_na(LATERALITY, HER2_STATUS, TUMOR_STAGE)
```
## 提取自变量
```{r}
predictors <- c("AGE_AT_DIAGNOSIS", "LATERALITY", "ER_STATUS", "HER2_STATUS",
                "TUMOR_STAGE")
```
## 建模
```{r}
map_dfr(predictors, \(x){
  f <- as.formula(paste0("TreatmentOutcome ~ ", x))
  fit <- glm(f, family = binomial(), data=data_analysis)

  broom::tidy(fit, conf.int=T, exponentiate=T) %>% filter(term != "(Intercept)")
})
```





