---
title: "Proj 02 Timely and Effective Care by US States"
output: html_document
---

# Step 1 数据理解与清洗
## 读取数据
```{r}
library(readr)

care <- read_csv("./data/care_state.csv")
```
## 检查数据 1
```{r}
head(care)
```

## 检查数据 2
```{r}
library(dplyr)

glimpse(care)
```

## 检查数据缺失值
```{r}
colSums(is.na(care))
```
## 剔除数据缺失值
```{r}
care_clean <- care %>%
  filter(!is.na(score))
colSums(is.na(care_clean))
```

# Step 2 单变量分析
## 对score做可视化（无分组）
```{r}
library(tidyverse)
ggplot(care_clean, aes(x = score)) +
  geom_histogram(bins = 40, fill = "steelblue")
```

## 对score做可视化（按照医疗场景进行分组）
```{r}
ggplot(care_clean, aes(x = score)) +
  geom_histogram(bins = 30, fill = "steelblue") +
  facet_wrap(~condition, scales = "free")
```

## 检查自变量分布
```{r}
care_clean %>%
  count(state) %>%
  ggplot(aes(x = reorder(state, n), y = n)) +
  geom_col() +
  coord_flip()
```

# Step 3 多变量分析
## 3.1 分析不同州医疗表现（急诊接待时间） - 数据清理1
```{r}
cond_1 <- "Emergency Department"

care_ed1 <- care_clean %>%
  filter(condition == cond_1)
```

## 3.2 分析不同州医疗表现（急诊接待时间） - 数据清理2
```{r}
cond_1 <- "Emergency Department"
cond_2 <- "OP_18"

care_ed2 <- care_clean %>%
  filter(condition == cond_1, str_detect(measure_id, cond_2))
```

## 3.3 分析不同州医疗表现（急诊接待时间） - 数据清理3
```{r}
cond_1 <- "Emergency Department"
cond_2 <- "OP_18c"

care_ed3 <- care_clean %>%
  filter(condition == cond_1, measure_id == cond_2)
```

## 3.4 分析不同州医疗表现（急诊接待时间） - 按州对比
```{r}
care_ed3 %>%
  ggplot(aes(x = reorder(state, score), y = score)) +
  geom_col(fill = "steelblue") +
  coord_flip()
```

## 3.5 分析同一个州不同医疗指标的差异 - 同一州内
```{r}
state_ <- "AK"
cond <- "Emergency Department"

care_clean %>%
  filter(state == state_, condition == cond) %>%
  ggplot(aes(x = reorder(measure_id, score), y = score)) +
  geom_col(fill = "tomato") +
  coord_flip()
```
## 3.6 分析同一个州不同医疗指标的差异 - 两个州的对比
```{r}
states <- c("AK", "AL")
cond <- "Emergency Department"

data_compare <- care_clean %>%
  filter(
    state %in% states,
    condition == cond,
  )  %>%
  group_by(measure_id) %>%
  filter(n_distinct(state) == 2) %>%  # 只保留同时存在AK和AL数据的指标
  ungroup()

ggplot(data_compare, aes(
  x = reorder(measure_id, score),
  y = score,
  fill = state
)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  coord_flip() +
  scale_fill_manual(
    values = c("AK" = "tomato", "AL" = "steelblue"),
    name = "State"
  ) + 
  labs(
    x = "指标ID",
    y = "Score",
    title = "AK vs AL 急诊科指标得分对比"
  ) +
  theme_minimal()
```


# Step 4 将分析组织成故事
## 4.1 数据清理 - 急诊科 + 等待中位时间（和3.3一致）
```{r}
cond_1 <- "Emergency Department"
cond_2 <- "OP_18c"

care_ed4 <- care_clean %>%
  filter(condition == cond_1, measure_id == cond_2)
```

## 4.2 建立整体印象 - 检查数据分布
```{r}
ggplot(care_ed4, aes(x = score)) +
  geom_histogram(bins = 30, fill = "steelblue")
```

## 4.3 按州比较等待时间差异
```{r}
care_ed4 %>%
  ggplot(aes(x = reorder(state, score), y = score)) +
  geom_col(fill = "tomato") +
  coord_flip()
```

## 4.5 微调图像
```{r}
care_ed4 %>%
  ggplot(aes(x = reorder(state, score), y = score)) +
  geom_col(fill = "tomato") +
  coord_flip() +
  labs(
    title = "Emergency Department Wait Time by State",
    x = "State",
    y = "Score"
  )
```


