---
title: "Proj 04 WHO TB Burden Data"
output: html_document
---
## 加载包
```{r}
library(tidyverse)
library(sf)
library(maps)
```



# 1 数据理解与流行病学指标理解
## 数据理解
```{r}
# 加载数据
tb <- read_csv("./data/who_tb_data.csv")

# 观察数据
glimpse(tb)

# 检查缺失值
colSums(is.na(tb))
```

## 流行病学指标
```{r}
# 发病计数
tb %>%
  arrange(desc(e_inc_num)) %>%
  select(country, year, e_inc_num) %>%
  head(10)

# 发病率
tb %>%
  arrange(desc(e_inc_100k)) %>%
  select(country, year, e_inc_100k) %>%
  head(10)

# 死亡率
countries_to_plot <- c("China", "Germany", "India", "South Africa", "United States of America")
tb_recent <- tb %>%
  filter(country %in% countries_to_plot, year == max(year, na.rm = TRUE)) %>%
  select(country, year, e_inc_100k, e_mort_100k) %>%
  rename(
    Incidence = e_inc_100k,
    Mortality = e_mort_100k
  )
print(tb_recent)

# 病死率
tb_cfr <- tb %>%
  filter(country %in% countries_to_plot, year == max(year, na.rm = TRUE)) %>%
  select(country, year,
         e_inc_100k,    # 每10万人发病率
         e_mort_100k,   # 每10万人死亡率
         cfr) %>%        # 数据自带的CFR字段
  mutate(
    # 用发病率和死亡率手动计算CFR
    calc_cfr = e_mort_100k / e_inc_100k,
    calc_cfr_pct = scales::percent(calc_cfr, accuracy = 0.01)
  ) %>%
  rename(
    incidence_per_100k = e_inc_100k,
    mortality_per_100k = e_mort_100k
  )
print(tb_cfr)
```

# 2 全球 TB burden 的空间分布
## 检查国家按年度平均发病率
```{r}
tb %>%
  group_by(country) %>%
  summarise(
    mean_incidence =
      mean(e_inc_100k, na.rm = TRUE)
  ) %>%
  arrange(desc(mean_incidence))
```

## 检查区域按年度平均发病率
```{r}
tb_region <- tb %>%
  group_by(g_whoregion) %>%
  summarise(
    mean_incidence = mean(e_inc_100k, na.rm = TRUE),
    mean_mortality = mean(e_mort_100k, na.rm = TRUE)
  )

ggplot(
  tb_region,
  aes(
    x = reorder(g_whoregion, mean_incidence),
    y = mean_incidence
  )
) +
  geom_col() +
  coord_flip()
```
## 地图可视化 - TB 发病率
```{r}
world_map <- map_data("world")

# 选择某个年份
tb_2023 <- tb %>%
  filter(year == 2023) %>%
  select(
    region = country,
    e_inc_100k
  )

# 国家名对齐
tb_2023 <- tb_2023 %>%
  mutate(
    region = case_when(
      region == "United States of America" ~ "USA",
      region == "Russian Federation" ~ "Russia",
      region == "United Kingdom of Great Britain and Northern Ireland" ~ "UK",
      region == "Viet Nam" ~ "Vietnam",
      region == "Democratic People's Republic of Korea" ~ "North Korea",
      region == "Republic of Korea" ~ "South Korea",
      region == "Iran (Islamic Republic of)" ~ "Iran",
      TRUE ~ region
    )
  )

# 合并地图与疾病数据
world_tb <- world_map %>%
  left_join(tb_2023, by = "region")

# 绘图
ggplot(world_tb,
       aes(x = long,
           y = lat,
           group = group)) +

  geom_polygon(aes(fill = e_inc_100k),
               color = "white",
               linewidth = 0.1) +

  coord_fixed(1.3) +

  scale_fill_viridis_c(
    option = "C",
    na.value = "grey90"
  ) +

  labs(
    title = "Global Tuberculosis Incidence",
    subtitle = "Estimated incidence per 100k population (2023)",
    fill = "TB incidence\n(per 100k)"
  ) +

  theme_void() +

  theme(
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 12)
  )


```
## 地图可视化 - TB 发病人数
```{r}
world_map <- map_data("world")

# 选择某个年份
tb_2023 <- tb %>%
  filter(year == 2023) %>%
  select(
    region = country,
    e_inc_num
  )

# 国家名对齐
tb_2023 <- tb_2023 %>%
  mutate(
    region = case_when(
      region == "United States of America" ~ "USA",
      region == "Russian Federation" ~ "Russia",
      region == "United Kingdom of Great Britain and Northern Ireland" ~ "UK",
      region == "Viet Nam" ~ "Vietnam",
      region == "Democratic People's Republic of Korea" ~ "North Korea",
      region == "Republic of Korea" ~ "South Korea",
      region == "Iran (Islamic Republic of)" ~ "Iran",
      TRUE ~ region
    )
  )

# 合并地图与疾病数据
world_tb <- world_map %>%
  left_join(tb_2023, by = "region")

# 绘图
ggplot(world_tb,
       aes(x = long,
           y = lat,
           group = group)) +

  geom_polygon(aes(fill = e_inc_num),
               color = "white",
               linewidth = 0.1) +

  coord_fixed(1.3) +

  scale_fill_viridis_c(
    option = "C",
    na.value = "grey90"
  ) +

  labs(
    title = "Global Tuberculosis Incidence Count",
    subtitle = "Estimated number of incident TB cases (2023)",
    fill = "TB cases"
  ) +

  theme_void() +

  theme(
    plot.title = element_text(size = 18, face = "bold"),
    plot.subtitle = element_text(size = 12)
  )


```


# 3 TB 的时间趋势分析
## 全球总体趋势
```{r}
tb_global <- tb %>%
  group_by(year) %>%
  summarise(
    total_incidence =
      sum(e_inc_num, na.rm = TRUE),
    total_mortality =
      sum(e_mort_num, na.rm = TRUE)
  )

ggplot(
  tb_global,
  aes(
    x = year,
    y = total_incidence
  )
) +
  geom_line()

ggplot(
  tb_global,
  aes(
    x = year,
    y = total_mortality
  )
) +
  geom_line()
```
## 将发病人数和死亡人数画到同一张图里：
```{r}
tb_long <- tb_global %>%
  pivot_longer(
    cols = c(total_incidence, total_mortality),
    names_to = "metric",
    values_to = "value"
  )

ggplot(
  tb_long,
  aes(
    x = year,
    y = value,
    color = metric
  )
) +
  geom_line()
```
## 国家层级的趋势分析
```{r}
tb_selected <- tb %>%
  filter(
    country %in%
      c("India", "China", "South Africa")
  )

ggplot(
  tb_selected,
  aes(
    x = year,
    y = e_inc_100k,
    color = country
  )
) +
  geom_line()
```




# 4 从疾病数量到疾病负担


# 5 HIV、人口与 TB 风险模式


# 6 把公共卫生分析组织成研究故事